[program:mynexthome]
user=admin
directory=/var/www
command=/var/www/venv/bin/gunicorn --bind 127.0.0.1:3001 MyNextHome.asgi:application -w 1 -k uvicorn.workers.UvicornWorker --timeout 300
autostart=true
autorestart=true
stdout_logfile=/var/www-logs/app.stdout.log
stderr_logfile=/var/www-logs/app.stderr.log