server {
    server_name mynexthome.daraza.net www.mynexthome.daraza.net;
    client_max_body_size 100M;
    location /static/ {
        alias /var/www/staticfiles/; 
    }

    location / {
        proxy_pass http://127.0.0.1:3001;  # Adjust to application's port
        include proxy_params;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }




    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mynexthome.daraza.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mynexthome.daraza.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot




}
server {
    if ($host = www.mynexthome.daraza.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = mynexthome.daraza.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name mynexthome.daraza.net www.mynexthome.daraza.net;
    listen 80;
    return 404; # managed by Certbot




}