# Generated by Django 5.1.3 on 2024-11-26 10:43

import ckeditor.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_email', models.EmailField(help_text='Management Email for the System', max_length=254)),
                ('root_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Management Phone Number for the system', max_length=128, region=None)),
                ('user_support_email', models.EmailField(help_text='User Support Email', max_length=254)),
                ('user_support_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='User Support Email', max_length=128, region=None)),
                ('transaction_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Transaction Phone', max_length=128, null=True, region=None)),
                ('sales_commission', models.PositiveIntegerField(default=7, help_text='Commissions charged for Items sold')),
                ('info', ckeditor.fields.RichTextField()),
                ('privacy_policy', ckeditor.fields.RichTextField()),
                ('terms_of_use', ckeditor.fields.RichTextField()),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Main Address')),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('address3', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=355, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('send_emails_alert', models.BooleanField(default=True)),
                ('use_gmail_smtp', models.BooleanField(default=True)),
                ('use_zoho_mail_smtp', models.BooleanField(default=False)),
                ('send_sms_alert', models.BooleanField(default=True)),
                ('use_twilio_sms', models.BooleanField(default=False)),
                ('use_africas_taking_sms', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SystemUtility',
                'verbose_name_plural': 'SystemUtility',
            },
        ),
        migrations.RenameField(
            model_name='update',
            old_name='image_illutrations',
            new_name='image_illustration',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_phone', to='core.systemutility'),
        ),
        migrations.AlterField(
            model_name='systememail',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_email', to='core.systemutility'),
        ),
        migrations.DeleteModel(
            name='InfoUtility',
        ),
    ]
