# Generated by Django 5.1.3 on 2024-11-26 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('f455207f-e757-4b5c-9a93-629b701baf1e'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
