# Generated by Django 5.1.3 on 2024-11-26 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('8ccdc5d7-b73e-4fae-b8c0-18a21173d551'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
