# Generated by Django 5.1.3 on 2024-11-28 14:56

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_is_processing_payments_is_processed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='receivers_phone',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('265dc191-1090-4e5f-ab91-8ea2810906ce'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reason', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='remittance_ledger', to='finance.ledger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remittance',
                'verbose_name_plural': 'Remittances',
            },
        ),
        migrations.DeleteModel(
            name='Refunds',
        ),
    ]
