# Generated by Django 5.1.3 on 2024-11-28 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payments_receivers_phone_alter_ledger_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('7bba4d60-e18f-4dac-aa40-ac9c13efa3dc'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
