# Generated by Django 5.1.3 on 2024-11-30 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('ad443f5f-d4a1-4c96-ac6f-8c7afd79a53d'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
