# Generated by Django 5.1.3 on 2024-12-05 23:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('a33f5995-9184-4ac2-b082-524e00393e32'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
