# Generated by Django 5.1.3 on 2024-12-10 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('41a9c035-0773-4120-9159-d54ed82f0177'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
