# Generated by Django 5.1.3 on 2024-12-12 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('284c6a85-35bf-49f6-888f-8eaf5b3beda0'), editable=False, unique=True, verbose_name='Transaction Id'),
        ),
    ]
