# Generated by Django 5.1.5 on 2025-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_ledger_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='user_to',
        ),
        migrations.RemoveField(
            model_name='remittance',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='MainWallet',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='points',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
