# Generated by Django 5.1.5 on 2025-05-22 21:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='nearby_landmarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('under_construction', 'Under Construction')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('short_term', 'Short Term Rental'), ('long_term', 'Long Term Rental')], default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='furnish_status',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi-Furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='internet_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='listed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.CreateModel(
            name='PropertyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR, GBP)', max_length=3)),
                ('usd_price', models.DecimalField(decimal_places=2, help_text='Price converted to USD', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('exchange_rate', models.DecimalField(decimal_places=6, help_text='Exchange rate when price was converted to USD', max_digits=10)),
                ('conversion_date', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('installments', 'Installments'), ('rent_to_own', 'Rent-to-Own')], default='cash', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
