# Generated by Django 5.1.3 on 2024-11-26 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='user_likes',
        ),
        migrations.CreateModel(
            name='PayLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Pay/%Y/%M/%d')),
                ('description', models.TextField(blank=True, verbose_name='Being Payment for')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
