# Generated by Django 5.1.3 on 2024-11-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_postfile_post_remove_userpost_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylink',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
