# Generated by Django 5.1.5 on 2025-05-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Designate the user as an owner'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_realtor',
            field=models.BooleanField(default=False, help_text='Designate the user as a realtor'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
