# Generated by Django 5.1.5 on 2025-05-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_creator_remove_user_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('Kenya', 'Kenya'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi'), ('South Sudan', 'South Sudan'), ('Ethiopia', 'Ethiopia'), ('Somalia', 'Somalia'), ('Eritrea', 'Eritrea'), ('Djibouti', 'Djibouti'), ('DR Congo', 'DR Congo')], default='Uganda', help_text='Country (East Africa only)', max_length=100),
        ),
    ]
