# Generated by Django 5.1.5 on 2025-11-24 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/compressed/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property_video_thumbnails/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_currency',
            field=models.CharField(choices=[('UGX', 'Ugandan Shilling'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('SSP', 'South Sudanese Pound'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('ERN', 'Eritrean Nakfa'), ('DJF', 'Djiboutian Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan')], default='UGX', help_text='Currency for the property price', max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
