# Generated by Django 5.1.3 on 2024-11-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_linktype_portfoliotype_paylink_link_pay_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paylink',
            old_name='link_pay',
            new_name='link_type',
        ),
    ]
