# Generated by Django 5.1.3 on 2024-11-30 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_link_pay_paylink_link_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created'], 'verbose_name': 'Business Profile', 'verbose_name_plural': 'Business Profiles'},
        ),
        migrations.AlterModelOptions(
            name='portfoliotype',
            options={'ordering': ['name'], 'verbose_name': 'Business Type', 'verbose_name_plural': 'Business Types'},
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='type',
            new_name='kind_of_business',
        ),
        migrations.AddField(
            model_name='paylink',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='portfoliotype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliotype',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
