# Generated by Django 5.1.5 on 2026-02-15 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='applies_to_commercial',
            field=models.BooleanField(default=False, help_text='Available for commercial properties'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='applies_to_hospitality',
            field=models.BooleanField(default=False, help_text='Available for hospitality properties'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='applies_to_residential',
            field=models.BooleanField(default=True, help_text='Available for residential properties'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium/Luxury amenity'),
        ),
        migrations.AddField(
            model_name='neighborhoodfeature',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from property in kilometers', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Standard check-in time', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Standard check-out time', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time cleaning fee', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_slots',
            field=models.PositiveIntegerField(blank=True, help_text='Number of parking/garage slots', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_storefront',
            field=models.BooleanField(default=False, help_text='Has street-facing storefront (for shops)'),
        ),
        migrations.AddField(
            model_name='property',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rental rate (for parking, meeting rooms, etc.)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='maximum_occupancy',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of guests (for hotels/Airbnb)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_stay_nights',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum stay requirement in nights', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rental rate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nightly rate (for hotels, Airbnb, etc.)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='office_spaces',
            field=models.PositiveIntegerField(blank=True, help_text='Number of individual office spaces/rooms', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Refundable security deposit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='shop_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shop/retail space size in sq ft', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='warehouse_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Warehouse storage capacity in cubic feet or tons', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='yearly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly rental/lease rate', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='default_pricing_model',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('per_night', 'Per Night'), ('per_hour', 'Per Hour'), ('per_month', 'Per Month'), ('per_year', 'Per Year'), ('per_sqft', 'Per Square Foot')], default='fixed', help_text='Default pricing model for this property type', max_length=20),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='is_commercial',
            field=models.BooleanField(default=False, help_text='Is this a commercial property type?'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='is_hospitality',
            field=models.BooleanField(default=False, help_text='Is this a hospitality property type?'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='is_residential',
            field=models.BooleanField(default=True, help_text='Is this a residential property type?'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show as featured amenity'),
        ),
        migrations.AlterField(
            model_name='neighborhoodfeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhoodfeature',
            name='is_essential',
            field=models.BooleanField(default=False, help_text='Essential service/feature'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, help_text='Number of bedrooms (0 for studio)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('short_term', 'Short Term Rental'), ('long_term', 'Long Term Rental'), ('hourly', 'Hourly Rental'), ('nightly', 'Nightly Rental'), ('monthly', 'Monthly Rental')], default='sale', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fa-home)', max_length=50, null=True),
        ),
    ]
