# Generated by Django 5.1.5 on 2026-02-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_amenity_applies_to_commercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
