# Generated by Django 5.1.3 on 2024-12-05 23:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_portfolio_last_verification_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(default=accounts.models.default_expiration_time)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
