# Generated by Django 5.1.5

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    PropertyType = apps.get_model('accounts', 'PropertyType')
    for pt in PropertyType.objects.all():
        if not pt.slug or pt.slug == "":
            base_slug = slugify(pt.name) or "property-type"
            slug = base_slug
            counter = 1
            # Check for existing slugs in the database to avoid duplicates
            while PropertyType.objects.filter(slug=slug).exclude(id=pt.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            pt.slug = slug
            pt.save()

def reverse_populate_slugs(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_propertytype_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
