# Generated by Django 5.1.3 on 2024-12-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_otpverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created'], 'verbose_name': 'User Portfolio', 'verbose_name_plural': 'User Portfolios'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='verified_phone',
            field=models.BooleanField(default=False),
        ),
    ]
