# Generated by Django 5.1.3 on 2024-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_portfolio_options_portfolio_verified_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='logo',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='Portfolio_Documents/%Y/%m/%d'),
        ),
    ]
