# Generated by Django 5.1.5 on 2026-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_populate_propertytype_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='has_bathrooms',
            field=models.BooleanField(default=True, help_text='Does this property type usually have bathrooms?'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_bedrooms',
            field=models.BooleanField(default=True, help_text='Does this property type usually have bedrooms?'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_floors',
            field=models.BooleanField(default=True, help_text='Does this property type have floors?'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='has_furnishing',
            field=models.BooleanField(default=True, help_text='Can this property type be furnished?'),
        ),
    ]
