# Generated by Django 5.1.3 on 2024-12-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_portfolio_logo_portfolio_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportuser',
            name='reporter',
        ),
        migrations.AddField(
            model_name='reportuser',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_link', to='accounts.paylink'),
        ),
    ]
